--M0521023_Gentur Sahadewa

CREATE TABLE BOOK_COPIES (
	[BookId]		INTEGER NOT NULL,
	[BranchId]		INTEGER NOT NULL,
	No_Of_Copies	INTEGER
);

ALTER TABLE BOOK_COPIES 
	ADD CONSTRAINT FK_COPIES_BOOK FOREIGN KEY ([BookId]) REFERENCES BOOK([BookId]);

CREATE TABLE LIBRARY_BRANCH (
	[BranchId]		INTEGER NOT NULL,
	[BranchName]	VARCHAR(64),
	[Address]		VARCHAR(64)
);

ALTER TABLE LIBRARY_BRANCH
	ADD CONSTRAINT PK_BRANCH PRIMARY KEY ([BranchId]);
ALTER TABLE BOOK_COPIES 
	ADD CONSTRAINT FK_COPIES_BRANCH FOREIGN KEY ([BranchId]) REFERENCES LIBRARY_BRANCH([BranchId]);

CREATE TABLE BOOK_LOANS (
	[BookId]		INTEGER NOT NULL,
	[BranchId]		INTEGER NOT NULL,
	[CardNo]		INTEGER NOT NULL,
	[DateOut]		Date,
	[DueDate]		Date
);

CREATE TABLE BORROWER (
	[CardNo]		INTEGER NOT NULL,
	[Name]			VARCHAR(64),
	[Address]		VARCHAR(64),
	[Phone]			VARCHAR(64)
);

ALTER TABLE BORROWER
	ADD CONSTRAINT PK_BORROWER PRIMARY KEY ([CardNo]);

ALTER TABLE BOOK_LOANS
	ADD CONSTRAiNT FK_BOOKLOANS_BOOKID FOREIGN KEY ([BookId]) REFERENCES BOOK([BookId]);

ALTER TABLE BOOK_LOANS
	ADD CONSTRAiNT FK_BOOKLOANS_BRANCHID FOREIGN KEY ([BranchId]) REFERENCES LIBRARY_BRANCH([BranchId]);

ALTER TABLE BOOK_LOANS
	ADD CONSTRAiNT FK_BOOKLOANS_CARDNO FOREIGN KEY ([CardNo]) REFERENCES BORROWER([CardNo]);

